### ISSUE TITLE
Consider adding Hudson Rock cybercrime intelligence integration

### ISSUE THREAD

**Issue by hudsonrock-partnerships** [joshhighet/ransomwatch#108]
Consider integrating Hudson Rock's complementary data from over 28 million computers infected by the Infostealer malware. 
One of the similar ransomware monitoring services already using our data to bring more useful insights to their community. 

The most relevant endpoint for your project can indicate how many compromised users and employees were affected by Infostealing malware before the ransomware incident.

Full API documentation is available here - https://cavalier.hudsonrock.com/docs
You will find the relevant information under the "Third Party Risk Assessment" tab on the left side of the menu. 
 
Thank you.

**Comment by joshhighet** [comment]
Considered. No.
