### ISSUE TITLE
new group:  Lynx

### ISSUE THREAD

**Issue by JMousqueton** [joshhighet/ransomwatch#110]
### host location

http://lynxbllrfr5262yvbgtqoyq76s7mpztcqkv6tjjxgpilpma7nyoeohyd.onion/leaks

### group name

Lynx

### group information

Based on Inc Ransom code source

Also a clearnet : http://lynxblog.net/leaks 

### host

v3 (onion)

### parser

```shell
grep -oP '(?<=<h4 class="chat__block-title" style="">).*?(?=</h4>)' source/lynx-*.html
```

**Comment by agelormini** [comment]
Hi, this group is named "lynx" on group lists but his posts are sent with "lynxblog" name.

Can you fix it?
