### ISSUE TITLE
new group: Orca

### ISSUE THREAD

**Issue by FacundoGregorini** [joshhighet/ransomwatch#114]
### host location

orca66hwnpciepupe5626k2ib6dds6zizjwuuashz67usjps2wehz4id.onion

### group name

Orca

### host

v3 (onion)

**Comment by JMousqueton** [comment]
@joshhighet 
the parser cmd line could be : 

`grep -oP '(?<=<h2 class="blog__card-top-info-title">)(.*?)(?=</h2>)' source/orca-*.html | grep -v INTRODUCTION`
