### ISSUE TITLE
new group: Nitrogen

### ISSUE THREAD

**Issue by FacundoGregorini** [joshhighet/ransomwatch#115]
### host location

nitrogenczslprh3xyw6lh5xyjvmsz7ciljoqxxknd7uymkfetfhgvqd.onion

### group name

Nitrogen

### host

v3 (onion)

**Comment by JMousqueton** [comment]
@joshhighet 
Parser cmd line could be : 

` grep -oP '(?<=<h3><b>)(.*?)(?=</b></h3>)' source/nitrogen-*.html`
