### ISSUE TITLE
Meow group not parsing correctly

### ISSUE THREAD

**Issue by agelormini** [joshhighet/ransomwatch#116]
Posts of Meow group seem stuck at 06/03/2024 but there are about 80 new posts on their onion site that are not listed. Even if is being actively scraped. Mybe there is some error in the parser

**Comment by JMousqueton** [comment]
@joshhighet  the parse command line could be : 

`grep -oP '(?<=<a href="javascript:;">)(.*?)(?=</a>)'  source/meow-*.html `
