### ISSUE TITLE
Was this repo hacked?

### ISSUE THREAD

**Issue by simeonyetarian1** [joshhighet/ransomwatch#15]
Why is suddenly every file changed with a random emoji as commit message and multiple files in the /docs/ folder are empty?

**Comment by joshhighet** [comment]
ha, no - just relocated from org to my profile :) 

I've stored and archived previous history, see [ransomwatch-history](https://github.com/joshhighet/ransomwatch-history) for prior data (may 2021-2022)

repo was nearing 2gb so made sense given the planned move to speed things back up a little.
