### ISSUE TITLE
exclude cl0p from /stats

### ISSUE THREAD

**Issue by joshhighet** [joshhighet/ransomwatch#18]
too many posts in series - challenges validity of the graphs (part 1/2/3/4 etc etc)

**Comment by Gizmo44z** [comment]
Will this just be in regards to the stats and graphs or recent posts as well?

**Comment by joshhighet** [comment]
hasn’t thought about that - worth removing from recent ports too?

**Comment by Gizmo44z** [comment]
I do find covering recent posts for as many groups as possible to be useful. Even as annoying as their post frequency is, I would prefer they stay on the recent posts.
