### ISSUE TITLE
Parser for Bailan Group

### ISSUE THREAD

**Issue by JMousqueton** [joshhighet/ransomwatch#25]
The parser for Bailan group doesn't work well with - (comma) or ' (single quote). Check the recent posts : 

2022-09-03 | s 
2022-08-30 | LLC 
2022-08-30 | group  

I suggest to replace the parse line with 

```
sed -n '/<a href="\/companies\//,/<\/a>/p' source/bianlian-*.html | egrep -o "([A-Za-z0-9 ,\'.-])+</a>" | cut -d '<' -f 1 | sed -e '/Contacts/d'
```

**Comment by joshhighet** [comment]
thanks. relates to use of `alnum` as seen in #17
