### ISSUE TITLE
Vicesociety latest entry not pulled

### ISSUE THREAD

**Issue by NeodymiumPhish** [joshhighet/ransomwatch#26]
The vicesociety site appears to be correct in Ransomwatch, but it failed to pull the latest entry (Los Angeles USD) from their leak site. 

vsociethok6sbprvevl4dlwbqrzyhxcxaqpvcqt5belwvsuxaxsutyad.onion

![image](https://user-images.githubusercontent.com/7989828/193324692-ad1d019c-7d06-4900-98f2-fc96cd3e1e71.png)

I'm not sure whether this is a parsing error, just wanted to point it out to try and help find a resolution.

**Comment by joshhighet** [comment]
thanks, resolved itself after a failed build
https://github.com/joshhighet/ransomwatch/blame/d3f5dcad015f47f10a7ec645ee0cc5eb484bbcad/posts.json#L24118
