### ISSUE TITLE
Historic data under Cuba ransomware

### ISSUE THREAD

**Issue by HastingsW72** [joshhighet/ransomwatch#34]
Historic data under cuba ransomware is being listed again on 2022-11-04

**Comment by HastingsW72** [comment]
<img width="513" alt="image" src="https://user-images.githubusercontent.com/113513398/200749912-0dcc7e11-db14-464b-8cf5-447182b08a95.png">

**Comment by joshhighet** [comment]
yes….. ref https://github.com/joshhighet/ransomwatch/issues/33
