### ISSUE TITLE
Make screenshotter.py works with onion sites

### ISSUE THREAD

**Issue by JMousqueton** [joshhighet/ransomwatch#36]
Original version doesn't seem to work due to an error in the NS Lookup function (not using Tor tunnel).
I modified the original version being inspired by the version of RansomLook. 
I'm sure the code could be lighter, I did not check if all import are still necessary.

Need playwrights : 
`pip3 -r install `
`playwright install`

I cannot do a PR because I modified so many things at the same time, sorry 👎🏻   

[screenshotter.py.txt](https://github.com/joshhighet/ransomwatch/files/10096873/screenshotter.py.txt)

**Comment by joshhighet** [comment]
solid - thanks @JMousqueton !
