### ISSUE TITLE
BlackBasta not showing new results

### ISSUE THREAD

**Issue by NeodymiumPhish** [joshhighet/ransomwatch#48]
The BlackBasta blog site (http://stniiomyjliimcgkvdszvgen3eaaoz55hreqqx6o77yvmpwt7gklffqd[.]onion/) is still up, but ransomwatch isn't pulling in any of the new results. I'm guessing the parser is looking in the wrong place or something. 

Could have been a change on BB's side, as clicking the name of a victim on their Tor site fails to resolve, but the names and some important info is still available from the main blog page that should be parseable.

**Comment by joshhighet** [comment]
good spotting, thanks
