### ISSUE TITLE
New parser for blackbytes

### ISSUE THREAD

**Issue by JMousqueton** [joshhighet/ransomwatch#49]
The blackbytes ransomware group has changed (again) their webpage. 

The vicitims'names could be found in class=target-name h1 tag. 

Here is a parser which seems to work fine (for now) : 

`grep --no-filename 'class="target-name"' source/blackbyte-*.html | cut -d '>' -f 2 | cut -d '<' -f 1 | sed -e 's/^ *//g' -e '/^$/d' -e 's/[[:space:]]*$//' `

**Comment by joshhighet** [comment]
thank you!
