### ISSUE TITLE
new group: Dark Power

### ISSUE THREAD

**Issue by JMousqueton** [joshhighet/ransomwatch#50]
### host location

http://powerj7kmpzkdhjg4szvcxxgktgk36ezpjxvtosylrpey7svpmrjyuyd.onion

### group name

Dark Power

### host

v3 (onion)

### parser

```shell
grep '<h2 class="title-font text-2xl font-medium text-white mt-6 mb-3">' source/darkpower-*  | cut -d '>' -f2 | cut -d '<' -f1
```

**Comment by joshhighet** [comment]
thanks as always @JMousqueton - I'll add if it comes back up and I can review

![Screenshot 2023-03-18 at 2 12 08 PM](https://user-images.githubusercontent.com/17993143/226075313-f8b64cba-5c41-4fce-9287-a5abcc55aaa0.png)

**Comment by joshhighet** [comment]
closing this - if it ever comes back up I will reopen, thx @JMousqueton
