### ISSUE TITLE
new group: 

### ISSUE THREAD

**Issue by danielxmnn** [joshhighet/ransomwatch#54]
### host location

http://h3reihqb2y7woqdary2g3bmk3apgtxuyhx4j2ftovbhe3l5svev7bdyd.onion/stm.html

### group name

Stormous.X

### group information

MESSAGE:
Did you get infected with STORMOUS ransomware? Are your company's server files encrypted? Is your computer encrypted? Are all your computer files encrypted? Read the decryption rules and all your files will be restored within an hour (Stormous.X can infect an entire network in less than an hour)

SHOP:
http://h3reihqb2y7woqdary2g3bmk3apgtxuyhx4j2ftovbhe3l5svev7bdyd.onion/shop.html

### host

v3 (onion)

**Comment by joshhighet** [comment]
thanks! closing as duplicate #53
