### ISSUE TITLE
new group: akira

### ISSUE THREAD

**Issue by joshhighet** [joshhighet/ransomwatch#56]
### host location

https://akiral2iz6a7qgd3ayp3l6yub7xx2uep76idk3u2kollpj5z3z636bad.onion/l

### group name

akira

### host

v3 (onion)

### parser

```shell
// awaiting first claim
```

**Comment by joshhighet** [comment]
fetch location appears to have changed https://github.com/joshhighet/ransomwatch/blob/main/source/akira-akiral2iz6a7qgd3ayp3l6yub7xx2uep76idk3u2kollpj5z3z636bad.html

ref tr https://twitter.com/sosintel/status/1650470919494684673

**Comment by GPS-Nic** [comment]
`https://akiral2iz6a7qgd3ayp3l6yub7xx2uep76idk3u2kollpj5z3z636bad.onion/n` appears to show their victims before they leak any data.
