### ISSUE TITLE
new group: Play Ransomware

### ISSUE THREAD

**Issue by milxss** [joshhighet/ransomwatch#58]
### host location

http://mbrlkbtq5jonaqkurjwmxftytyn2ethqvbxfu4rgjbkkknndqwae6byd.onion

### group name

Play Ransomware

### group information

Hi, can you please add "Play" to Ransomwatch? The group is relatively new, it started being active in mid 2022. It has a number of major victims, like BMW France or CH Media.

Here is their blog:
http://mbrlkbtq5jonaqkurjwmxftytyn2ethqvbxfu4rgjbkkknndqwae6byd.onion

Thanks,
Kamila

### host

v1 (onion)

**Comment by GPS-Nic** [comment]
Hi @milxss, Play is already tracked in Ransomwatch, including that same leak site. 

Here's their profile: https://ransomwatch.telemetry.ltd/#/profiles?id=play
