### ISSUE TITLE
new group:  Malas

### ISSUE THREAD

**Issue by JMousqueton** [joshhighet/ransomwatch#62]
### host location

malas2urovbyyavjzaezkt5ohljvyd5lt7vv7mnsgbf2y4bwlh72doqd.onion

### group name

Malas

### group information

list of vicitms :  http://malas2urovbyyavjzaezkt5ohljvyd5lt7vv7mnsgbf2y4bwlh72doqd.onion/posts/ 

### host

v3 (onion)

### parser

```shell
grep '<a class="link" href=' sources/malas-*.html  --no-filename | cut -d '>' -f2
```

**Comment by joshhighet** [comment]
thanks @JMousqueton - you 🌟
