### ISSUE TITLE
New group

### ISSUE THREAD

**Issue by ErezDasa** [joshhighet/ransomwatch#63]
### host location

nokoleakb76znymx443veg4n6fytx6spck6pc7nkr4dvfuygpub6jsid

### group name

Nokoyawa

### host

v3 (onion)

**Comment by maiqueg** [comment]
Thanks for sharing, this is not a new group, however the onion address is new! 

Also the page changed from the last version and here's the updated parser:
`grep -Eo 'class="text-5xl font-semibold">.*' source/nokoyawa-*.html | cut -d'<' -f1 | cut -d'>' -f2`

**Comment by joshhighet** [comment]
thanks @ErezDasa !

you can also find this at `/api/leaks/get` on `noko65rmtaiqyt2cw2h4jrxe3u56t2k7ov3nd22hoji4c5vnfib2i4yd`

I have added both sites but have chosen to use the API response for now - thanks heaps for the parser though @maiqueg !

```shell
curl --silent --socks5-hostname telemetry.dark:9050 \
noko65rmtaiqyt2cw2h4jrxe3u56t2k7ov3nd22hoji4c5vnfib2i4yd.onion/api/leaks/get \
| jq -r '.payload[].title' | sed 's/%20/ /g'
```
