### ISSUE TITLE
new group: 8BASE

### ISSUE THREAD

**Issue by maiqueg** [joshhighet/ransomwatch#64]
### host location

basemmnnqwxevlymli5bs36o5ynti55xojzvn246spahniugwkff2pad.onion

### group name

8BASE

### group information

[https://twitter.com/8BASEHOME](url)
[https://twitter.com/Threatlabz/status/1660687100394766336](url)

### host

v3 (onion)

### parser

```shell
awk '/class="stretched-link">/{getline; print}' source/8base-*.html | sed -e 's/^[ \t]*//'
```

**Comment by joshhighet** [comment]
thanks @maiqueg ! ❤️
