### ISSUE TITLE
new group: Rhysida

### ISSUE THREAD

**Issue by yoryio** [joshhighet/ransomwatch#66]
### host location

rhysidafohrhyy2aszi7bm32tnjat5xri65fopcxkdfxhi4tidsg7cad.onion

### group name

Rhysida

### group information

New ransomware group spotted in the Dark Web.
This group doesn't list their victims in their website.

### host

v3 (onion)

**Comment by yoryio** [comment]
The ransomware group is currently posting some victims and leaks.

**Comment by JMousqueton** [comment]
Here is the url of leak : http://rhysidafohrhyy2aszi7bm32tnjat5xri65fopcxkdfxhi4tidsg7cad.onion/archive.php

and the parse : 

`grep "m-2 h4" source/rhysida-* | cut -d '>' -f 3 | cut -d '<' -f 1 `

**Comment by nuke86** [comment]
This address is also to be considered among the additions: http://rhysidafohrhyy2aszi7bm32tnjat5xri65fopcxkdfxhi4tidsg7cad.onion/archive.php?auction

with the same parser
