### ISSUE TITLE
Dark race group

### ISSUE THREAD

**Issue by ErezDasa** [joshhighet/ransomwatch#67]
### host location

http://wkrlpub5k52rjigwxfm6m7ogid55kamgc5azxlq7zjgaopv33tgx2sqd.onion

### group name

Dark race

### host

v3 (onion)

**Comment by JMousqueton** [comment]
here is the parser : 

egrep -o '<a class="post-title-link" href="/[^"]+">[^<]+</a>' source/darkrace-*  | cut -d'>' -f 2 | cut -d '<' -f 1
