### ISSUE TITLE
new group: La Piovra

### ISSUE THREAD

**Issue by JMousqueton** [joshhighet/ransomwatch#70]
### host location

h3txev6jev7rcm6p2qkxn2vctybi4dvochr3inymzgif53n2j2oqviqd.onion

### group name

La Piovra 

### group information

Old post (06/2022) 

### host

v3 (onion)

### parser

```shell
grep "entry-title" source/la_piovra-* | cut -d '>' -f 3 | cut -d '<' -f 1
```

**Comment by joshhighet** [comment]
thanks Julien - I've been on holiday and just catching up on things here, it looks offline for now - I will check periodically and add once I see activity

**Comment by soufianetahiri** [comment]
Turned out this is not a ransomware group but an Offsec exercise https://twitter.com/S0ufi4n3/status/1668474430517915648

**Comment by joshhighet** [comment]
> Turned out this is not a ransomware group but an Offsec exercise https://twitter.com/S0ufi4n3/status/1668474430517915648

lmao. i see, thanks
