### ISSUE TITLE
Commit 5dabbea reintroduced 3 month old victims?

### ISSUE THREAD

**Issue by basvanschaik** [joshhighet/ransomwatch#71]
Hi there, 

It seems that in commit 5dabbea you reintroduced some Qilin victims, like www.attentzorgenbehandeling.nl and fsmsolicitors.co.uk. They appear with a discovered date of 2023-06-15. Both these where already mentioned as victims on 2023-03-01, and the latest victim on the Qilin blog is from 9 june 2023.

Is this a bug perhaps?

**Comment by joshhighet** [comment]
Good spotting, Thanks. The original parser was capturing the URL prefix incorrectly which led to seemingly duplicate entries.
