### ISSUE TITLE
Question: obtaining evidence

### ISSUE THREAD

**Issue by SecT0uch** [joshhighet/ransomwatch#74]
We are a "Group DIS" customer and it seems data leaks occurred the 15/05/2023 and 17/05/2023 via alphv website.

We suspect the company not being transparent, they claim no data leak occurred.
I can't find any document linked to group DIS on alphv website, but we suspect the leak did occur and the ransom was paid afterwards, so the data has been removed.

I'm unfortunately discovering ransomwatch only now and was not running it to get evidences.

Is there any chance we can still get a proof of the leak ? 

The only document I find is a [copy of the webpage](https://github.com/joshhighet/ransomwatch/blob/main/source/alphv-vqifktlreqpudvulhbzmc5gocbeawl67uvs2pttswemdorbnhaddohyd.html), that's calling a javascript. So we have no useful information.

We can of course prove our legitimacy.

Great project BTW! :) 

Edit: Also available via jordan@sect0uch.world

**Comment by maiqueg** [comment]
Just sent you an email with the information that I found
